"""Dump the English source text and refresh the review file.

Reads the game's own en/Game.locres, pairs every entry with whatever is already
in translations/pl.json, and writes translations/en-pl-review.json: one row per
entry, English beside Polish, in the resource's own order.

Keys are 32-character hashes generated by the engine, so the namespace is what
gives a row its context - UIStringTable is the menu, Dialogue_Subs the subtitles,
CODEX the readable entries, and so on.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import locres

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'translations/en.locres',
                        help='The game\'s own en/Game.locres, extracted from the pak')
    args = parser.parse_args()

    english = locres.load(args.source)
    polish_path = ROOT / 'translations/pl.json'
    polish = {}
    if polish_path.exists():
        polish = {(row['namespace'], row['key']): row['polish']
                  for row in json.loads(polish_path.read_text(encoding='utf-8'))}

    rows, translated = [], 0
    for namespace, entry in english.entries():
        row = {'namespace': namespace, 'key': entry.key, 'english': entry.text}
        if (namespace, entry.key) in polish:
            row['polish'] = polish[(namespace, entry.key)]
            translated += 1
        rows.append(row)

    out = ROOT / 'translations/en-pl-review.json'
    out.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    by_namespace = {}
    for row in rows:
        counts = by_namespace.setdefault(row['namespace'] or '(none)', [0, 0])
        counts[0] += 1
        counts[1] += 'polish' in row
    print(json.dumps({'entries': len(rows), 'translated': translated,
                      'english_characters': sum(len(r['english']) for r in rows),
                      'namespaces': {k: f'{v[1]}/{v[0]}' for k, v in by_namespace.items()},
                      'output': str(out)}, ensure_ascii=False))


if __name__ == '__main__':
    main()
