from full_helpers import save
import json
from pathlib import Path
rows=json.loads(Path('games/sprawl/work/codex_pending.json').read_text(encoding='utf-8'))
def entry(index,text):save('CODEX',rows[index]['key']+'\t'+text.replace('\n','\\n'))
entry(36,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; ROZKAZY <red>PRZECHWYCIĆ OBIEKT SEVEN</> OBIEKT SEVEN ZIDENTYFIKOWANO JAKO AGENTKĘ POZIOMU GHOST. PRZECHWYCIĆ ZA WSZELKĄ CENĘ. OBECNA ANALIZA WSKAZUJE, ŻE SEVEN NIE JEST ODPOWIEDNIO WYPOSAŻONA. NALEŻY WYKORZYSTAĆ TĘ PRZEWAGĘ.<blink>_</>''')
entry(37,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; ROZKAZY <red>ZNEUTRALIZOWAĆ WSZYSTKIE WYZNACZONE OSOBY//UTRZYMAĆ POZYCJE OBRONNE</> W SEKTORACH OD R-2249 DO 5425-HSF WYZNACZONO CELE PRIORYTETOWE DO LIKWIDACJI PRZEZ PRECYZYJNE GRUPY UDERZENIOWE. NETRUNNERZY ZOSTANĄ ZNEUTRALIZOWANI ZŁOŚLIWYM OPROGRAMOWANIEM. KOLEJNE ZESPOŁY UDAJĄ SIĘ NA ICH POZYCJE, BY POTWIERDZIĆ LIKWIDACJĘ. PRZEJĘCIE LOKALNYCH SYSTEMÓW ROZPOCZNIE SIĘ GODZINĘ PRZED OPERACJĄ. ZGŁOSZONO KILKA ANOMALNYCH INCYDENTÓW W RÓŻNYCH MIEJSCACH. PROGNOZY WSKAZUJĄ, ŻE POTENCJALNY CEL ZMIERZA DO MIEJSCA PRZECHWYCENIA. W ZASIĘGU MUSI ZNAJDOWAĆ SIĘ KILKA ODDZIAŁÓW, ABY POTWIERDZIĆ TOŻSAMOŚĆ I ZLIKWIDOWAĆ CEL. MOŻLIWY ZBUNTOWANY ŻNIWIARZ.<blink>_</>''')
entry(38,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; ROZKAZY <red>ZNEUTRALIZOWAĆ WSZYSTKIE WYZNACZONE OSOBY</> W SEKTORACH OD 23-C DO 55-H WYZNACZONO CELE PRIORYTETOWE DO LIKWIDACJI PRZEZ PRECYZYJNE GRUPY UDERZENIOWE. NETRUNNERZY ZOSTANĄ ZNEUTRALIZOWANI ZŁOŚLIWYM OPROGRAMOWANIEM PRZED UDERZENIAMI ALPHA-DELTA. KOLEJNE ZESPOŁY UDAJĄ SIĘ NA ICH POZYCJE, BY POTWIERDZIĆ LIKWIDACJĘ. PRZEJĘCIE LOKALNYCH SYSTEMÓW ROZPOCZNIE SIĘ GODZINĘ PRZED OPERACJĄ. ZIDENTYFIKOWANO TRZY CELE WYSOKIEGO RYZYKA: ANALIZA WSKAZUJE, ŻE SEVEN NIE MA PROGRAMOWEGO DOSTĘPU DO WOJSKOWYCH WSZCZEPÓW <amber>[GHOST_TIER]</> W WYNIKU USUNIĘCIA Z PROGRAMU ŻNIWIARZ. ANALIZA WSKAZUJE, ŻE OSOBNIK 3251 MA POWAŻNE LUKI BEZPIECZEŃSTWA W PORTACH 2034, 3395, 2094. ATAKI NETRUNNERÓW PRAWDOPODOBNIE BĘDĄ SKUTECZNE. ANALIZA WSKAZUJE, ŻE OSOBNIK 35301 MA DOSTĘP DO WOJSKOWYCH WSZCZEPÓW <amber>[COMBAT1_TIER]</>. NETRUNNER ROZMIESZCZONY PRZY PUNKCIE WEJŚCIA URUCHOMI ZABEZPIECZENIA I JE WYŁĄCZY. <blink>_</>''')
entry(39,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; ROZKAZY <red>PACYFIKACJA</> WYSŁAĆ SIŁY PACYFIKACYJNE DO SEKTORÓW OD S-23 DO S-928. WSZYSTKIE KWARTAŁY OBJĘTE DZIESIĄTKOWANIEM. DZIAŁALNOŚĆ REBELIANTÓW NIE BĘDZIE TOLEROWANA. OSIĄGNĄĆ PEŁNĄ PACYFIKACJĘ ZA WSZELKĄ CENĘ. KOMÓRKI NULLSECT I IMAGO DEI UZNANO ZA GŁÓWNYCH PODŻEGACZY W TYM OBSZARZE. STRATY WŚRÓD CYWILÓW DOPUSZCZALNE W DOWOLNEJ SKALI. PRZED WKROCZENIEM ZABLOKOWAĆ WSZYSTKIE SZLAKI TRANSPORTOWE. ZIDENTYFIKOWANO JEDEN CEL NALOTU JAKO KLUCZOWEGO WSPÓŁPRACOWNIKA NULLSECT. WYSŁAĆ ODDZIAŁ W CELU UJĘCIA I LIKWIDACJI. <blink>_</>''')
entry(40,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; NCO powstało w wyniku serii korporacyjnych „zastępczych wojen domowych” w regionie, zakończonych wojskowym zamachem stanu. Przewrót odebrał kilku megakorporacjom wieloletnie wpływy i władzę, zmuszając każdą z nich do zawarcia niepewnego sojuszu z nową juntą. Wspólnie skupiono się na stabilizacji regionu oraz wyparciu wpływów Imperium Amerykańskiego i jego korporacyjnych potęg. Szpiegostwo wojskowe i nasilające się akty terroryzmu ze strony kilku grup podziemnych oraz sąsiednich miast-państw doprowadziły do powstania specjalnych programów wojskowych opracowywanych wspólnie z tymi megakorporacjami.<blink>_</>''')
entry(41,'''Dostęp wojskowy 40-a &lt;tpr-A21H.43.21.123&gt; SPRAWL — nazwa megapolis rozciągającej się od wybrzeża dzisiejszego <red>UTAJNIONO</> na nieokreśloną odległość w głąb lądu — jest jednym z ostatnich reliktów minionej epoki państwowości. Większość współczesnych państw upadła, znaczne obszary Ziemi nie nadają się do życia, a faktycznym porządkiem stała się odmiana neofeudalizmu z korporacyjnymi miastami-państwami. Istotnymi wyjątkami są Imperium Amerykańskie, luźny konglomerat dawnych stanów i terytoriów USA, obejmujący obecnie także Kanadę i część Ameryki Południowej, oraz NCO — azjatycka dyktatura wojskowa. Oba państwa są niezwykle wielokulturowe za sprawą licznych imigrantów rozpaczliwie tęskniących za stabilnością dawnego świata.''')
wall='''Dyrektywa dowództwa garnizonu//Hlford
Do: Dowódca posterunku 6-d
<red>SYS.ERROR.CORRUPT.REDIRECT//INFODOCWALLEDCITY</><amber>00000101239ghly</>
cechy agresywne, które zazwyczaj stanowią genetyczny ślepy zaułek z powodu wyjątkowo wysokiej śmiertelności.
Epidemia doprowadziła do ścisłej kwarantanny rozległych obszarów na najdalszych obrzeżach SPRAWL. Wzniesiono olbrzymie betonowe mury, by powstrzymać rozprzestrzenianie się zakażonych. Ponad milion osób zginęło w tej ostatecznie bezcelowej demonstracji drakońskich metod. Z czasem ta część miasta stała się siedliskiem przestępczości, produkcji narkotyków, czarnorynkowych wszczepów, prostytucji i hazardu.
Występki te można było znaleźć gdzie indziej, ale nie w takiej postaci. Chorej, wynaturzonej, skrajnej. Ludzie, którzy wybierali to miejsce na dom, najczęściej byli dzikimi lokatorami lub stanowczo nie chcieli zostać odnalezieni. <red>SYS.MALFORMED.USER.FORCE.DISCONNECT</><blink>_</>'''
entry(42,wall)
entry(43,'''Przewidywane niepowodzenie operacji:

Dyrektywa dowództwa garnizonu
Do: Dowódca posterunku 432-a
<red>SYS.ERROR.CORRUPT.REDIRECT//INFODOCSPIRE</><amber>00000152364h</>
Po tym incydencie junta, coraz bardziej paranoicznie obawiająca się kolejnej destabilizacji wywołanej przez własne zasoby, zaczęła weryfikować członków korporacyjnej elity. Zaczęto lękać się sabotażu ze strony ukrytych komórek wewnątrz samego rządu. Rozpoczęły się czystki. Wszystkich pozostałych członków elit miano zreorganizować i przenieść do centrum SPRAWL, gdzie pośrodku ogromnego cylindrycznego wykopu zaczęto wznosić przytłaczający monolit. Miała to być IGLICA — symbol militarnej potęgi junty i wieża strażnicza panoptykonu, w którym pod pozorem „bezpieczeństwa” zamknięto by elity. Junta zachowała kontrolę za niewyobrażalną cenę nad pogrążonym w stagnacji, rozbitym społeczeństwem. Rozpadły się wszelkie pozory tradycyjnej formy rządów. Zostali jedynie starcy udający, że rządzą światem.
<red>SYS.MALFORMED.USER.FORCE.DISCONNECT</><blink>_</>''')
entry(44,'''Przewidywane niepowodzenie operacji:

Dyrektywa dowództwa garnizonu
Do: Dowódca posterunku 432-a
<red>SYS.ERROR.CORRUPT.REDIRECT//INFODOCbad.LANDS</><amber>000001eyw74664h</>
W roku <red>[UTAJNIONO]</> cały przemysł ciężki przeniesiono na odległe tereny poza SPRAWL, aby wszystkie kontrakty wojskowe realizowano w kontrolowanym środowisku. Zrobiono to na mocy dekretu junty. Mniejsze korporacje, które nie mogły się tam przenieść, zostały wchłonięte lub zlikwidowane przez ostatnich wielkich wykonawców rządowych. Domand Corp było niegdyś znaczącym konkurentem i producentem broni, z dużą częścią potencjału produkcyjnego skupioną w tym regionie. Wiele dawnych zakładów Domand działa teraz autonomicznie po wrogim przejęciu przez korporację AEON.
<red>SYS.MALFORMED.USER.FORCE.DISCONNECT</><blink>_</>''')
entry(45,'''Budowę Iglicy ukończono <red>UTAJNIONO</>, a otaczającą ją infrastrukturę wcześniej, <red>UTAJNIONO</>. Deklarowanym celem projektu Iglicy, kierowanego przez Maurice'a Padillę-Fonga, było stworzenie chronionego centrum dla rdzenia junty i korporacyjnych elit: „niezwykłego symbolu trwałej stabilności zapewnianej przez juntę, jedności interesów korporacji i państwa, który promieniowałby tą wspaniałością na całe SPRAWL i budził lęk w sercach wrogów naszej ludowej junty”. Audyty dostarczonych zasobów oraz szpiegostwo korporacyjne dowiodły jednak, że AEON odegrało istotną rolę w projektowaniu budowli. W nadmiarze dostarczono wiele zasobów nietypowych dla deklarowanego przeznaczenia obiektu i otaczającej go megastruktury. Ustaliliśmy, że wewnątrz Iglicy najprawdopodobniej zaangażowano ogromne zasoby obliczeniowe.

<red>nieoczekiwane przerwanie połączenia, kod 0x4e712fe9</> <blink>_</>''')
entry(46,'Awaria wodociągu w strefie 6:\n\n'+wall)
